name: ci
on:
  push:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run tests"
        default: false
        required: false
        type: boolean
      additional_tests:
        description: "Run additional tests"
        default: false
        required: false
        type: boolean
      build_app:
        description: "Build app"
        default: false
        required: false
        type: boolean
      build_docs:
        description: "Build docs"
        default: false
        required: false
        type: boolean

jobs:
  run_tests:
    name: Run tests
    if: ${{
      github.event_name == 'workflow_dispatch' && inputs.run_tests ||
      github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip tests')
      }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh
      - name: Run tests
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        # run: bash ./scripts/run_tests.sh -c -r ${{ github.job }}
        run: bash ./scripts/run_tests.sh -r ${{ github.job }}

  additional_tests:
    strategy:
      fail-fast: false
      matrix:
        node: [ 20 ]
        mongo: [ 8 ]
    name: Additional tests
    if: ${{
      github.event_name == 'workflow_dispatch' && inputs.additional_tests ||
      github.event_name == 'push' && contains(github.event.head_commit.message, 'additional tests')
      }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh -n ${{ matrix.node }}
      - name: Run tests
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/run_tests.sh -n ${{ matrix.node }} -m ${{ matrix.mongo }}

  build_app:
    strategy:
      fail-fast: false
      matrix:
        node: [ 20 ]
        debian: [ 'bookworm' ]
    name: Build app
    if: ${{
      github.event_name == 'workflow_dispatch' && inputs.build_app ||
      github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip app')
      }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh
      - name: Build app
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/build_app.sh -n ${{ matrix.node }} -d ${{ matrix.debian }} -p -r ${{ github.job }}

  build_docs:
    name: Build docs
    if: ${{
      github.event_name == 'workflow_dispatch' && inputs.build_docs ||
      github.event_name == 'push' && contains(github.event.head_commit.message, 'doc')
      }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh
      - name: Build docs
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/build_docs.sh -p -r ${{ github.job }}
